<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <EditorConfigFiles Remove="C:\Users\User\Desktop\ASP.NET\RAIDAR_FRONT\.editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <None Include="C:\Users\User\Desktop\ASP.NET\RAIDAR_FRONT\.editorconfig" />
  </ItemGroup>

</Project>
